services:
  backend:
    build:
      context: ./beautirag-app/src/backend
      dockerfile: Dockerfile
    container_name: beautirag-backend
    env_file:
      - ./beautirag-app/.env
    # Mount the data directory as a volume to persist the FAISS index and processed files
    volumes:
      - ./beautirag-app/src/backend/data:/app_root/backend/data
    ports:
      - "8000:8000"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8000/"]
        interval: 300s
        timeout: 10s
        retries: 3
        start_period: 30s
    restart: unless-stopped

  frontend:
    build:
      context: ./beautirag-app
      dockerfile: Dockerfile
    container_name: beautirag-frontend
    ports:
      - "3000:3000"
    depends_on:
      backend:
          condition: service_healthy
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:8000
    restart: unless-stopped